name: food_ordering
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.0.0  # (I adjusted this slightly to be safe, usually ^3.0.0 is better than 3.9.0 if you don't have that specific version yet)

dependencies:
  flutter:
    sdk: flutter

  # Icons
  cupertino_icons: ^1.0.8

  # State Management
  provider: ^6.1.1

  # Fonts & Firebase (NOTICE THE SPACES BEFORE THESE LINES)
  google_fonts: ^6.1.0
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  cloud_firestore: ^4.15.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/